---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rss-app
spec:
  accessModes:
  - ReadWriteOnce
  dataSource: null
  resources:
    requests:
      storage: 1Gi
  #storageClassName: xxxx
  volumeMode: Filesystem
