name: build

on: push
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: MyAlbum/purge-cache@v1
        with:
          max-age: 1
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Install Cosign
        uses: sigstore/cosign-installer@main
        with:
          cosign-release: 'v2.4.0'
      #- name: Clone upstream
      #  run: git clone https://github.com/FreshRSS/FreshRSS.git freshrss-upstream
      - name: Login Build Push FreshRSS
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}" ${MTR}
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          docker build -t ghcr.io/${{ github.repository_owner }}/${REPO}/${IMAGE}:${VERSION} -f ./Docker/Dockerfile-k8s .
          docker push ghcr.io/${{ github.repository_owner }}/${REPO}/${IMAGE}:${VERSION}
          docker tag ghcr.io/${{ github.repository_owner }}/${REPO}/${IMAGE}:${VERSION} ${MTR}/${MTRREPO}:${VERSION}
          docker push ${MTR}/${MTRREPO}:${VERSION}
          cosign sign --key env://COSIGN_KEY --tlog-upload=false ${MTR}/${MTRREPO}:${VERSION}
          cosign sign --key env://COSIGN_KEY --tlog-upload=false ghcr.io/${{ github.repository_owner }}/${REPO}/${IMAGE}:${VERSION}
        env:
          COSIGN_KEY: ${{secrets.COSIGN_KEY}}
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
          REPO: freshrss-k8s
          IMAGE: fresh-rss
          MTR: mtr.devops.telekom.de
          MTRREPO: mcsps/fresh-rss
      - name: Login Build Push Python
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}" ${MTR}
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          mkdir tmp; cd tmp
          docker build -t ghcr.io/${{ github.repository_owner }}/${REPO}/${IMAGE}:${VERSION} -f ../Docker/Dockerfile-python .
          docker push ghcr.io/${{ github.repository_owner }}/${REPO}/${IMAGE}:${VERSION}
          docker tag ghcr.io/${{ github.repository_owner }}/${REPO}/${IMAGE}:${VERSION} ${MTR}/${MTRREPO}:${VERSION}
          docker push ${MTR}/${MTRREPO}:${VERSION}
          cosign sign --key env://COSIGN_KEY --tlog-upload=false ${MTR}/${MTRREPO}:${VERSION}
          cosign sign --key env://COSIGN_KEY --tlog-upload=false ghcr.io/${{ github.repository_owner }}/${REPO}/${IMAGE}:${VERSION}
        env:
          COSIGN_KEY: ${{secrets.COSIGN_KEY}}
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
          REPO: freshrss-k8s
          IMAGE: python-curl
          MTR: mtr.devops.telekom.de
          MTRREPO: mcsps/python-curl
